# Run `pre-commit install` to set up Git hooks locally.
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: forbid-ellipses
        name: Forbid ellipsis tokens in staged Python files
        entry: python -c "import sys; from pathlib import Path; token = chr(46) * 3; files = sys.argv[1:]; bad = [p for p in files if token in Path(p).read_text(encoding='utf-8')];\nimport sys as _sys;\nif bad:\n    print('Ellipsis tokens are forbidden in the following files: ' + ', '.join(bad))\n    _sys.exit(1)"
        language: python
        types: [python]
        pass_filenames: true
