name: CI

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv pip install -e .[dev]
      - name: Lint
        run: |
          ruff check src tests
          black --check src tests
          mypy src
      - name: Ensure no ellipsis stubs
        run: |
          grep -R "\\.\\.\\." --include="*.py" . && exit 1 || true
      - name: Test
        run: pytest -q --disable-warnings
      - name: Coverage upload
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

  nightly-refresh:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run refresh
        env:
          ODDS_API_KEY: ""
        run: |
          python -m ufc_winprob.pipelines.daily_refresh --mock
